// MOZE DA SE UDJE U NODE!!!
// DOLE U TERMINALU SE SAMO KUCA KOMANDA NODE PA ENTER!!!
// IZLAZI SE IZ NODE-A CTRL+C DVA PUTA!!!
// IZLAZI SE TAKODJE NA CTRL + D!!!
// IZLAZAK IZ NODE TAKODJE I KOMANDNOM .exit
// sve je case sensitive